-- MySQL Script generated by MySQL Workbench
-- Fri May 28 12:35:38 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProjectOneDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProjectOneDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjectOneDB` DEFAULT CHARACTER SET utf8 ;
USE `ProjectOneDB` ;

-- -----------------------------------------------------
-- Table `ProjectOneDB`.`Device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectOneDB`.`Device` (
  `DeviceId` VARCHAR(45) NOT NULL,
  `Naam` VARCHAR(45) NULL,
  `Merk` VARCHAR(45) NULL,
  `Beschrijving` VARCHAR(45) NULL,
  `Type` VARCHAR(45) NULL,
  `Meeteeneid` VARCHAR(45) NULL,
  PRIMARY KEY (`DeviceId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectOneDB`.`Acties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectOneDB`.`Acties` (
  `ActieId` VARCHAR(45) NOT NULL,
  `ActieBeschrijving` VARCHAR(145) NULL,
  PRIMARY KEY (`ActieId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectOneDB`.`Historiek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectOneDB`.`Historiek` (
  `HistoriekId` INT NOT NULL AUTO_INCREMENT,
  `DeviceId` VARCHAR(45) NOT NULL,
  `ActieId` VARCHAR(45) NOT NULL,
  `Waarde` FLOAT NULL,
  `Actiedatum` DATETIME NULL DEFAULT Now(),
  INDEX `fk_Historiek_Device_idx` (`DeviceId` ASC),
  INDEX `fk_Historiek_Acties1_idx` (`ActieId` ASC),
  PRIMARY KEY (`HistoriekId`),
  CONSTRAINT `fk_Historiek_Device`
    FOREIGN KEY (`DeviceId`)
    REFERENCES `ProjectOneDB`.`Device` (`DeviceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Historiek_Acties1`
    FOREIGN KEY (`ActieId`)
    REFERENCES `ProjectOneDB`.`Acties` (`ActieId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
